// Generated by Claude 3.5

#include <stdio.h>
#include <stdlib.h>

// const global array
const int grades[5] = {85, 90, 75, 95, 88};
const int num_students = 5;

void printGrades(int idx) {
    printf("Student grades:\n");
    printf("Student %d: %d\n", idx, grades[idx - 1]);
}

int main(int argc, char *argv[]) {
    if (argc != 2) {
        printf("Usage: %s <index>\n", argv[0]);
        return 1;
    }
    int idx = atoi(argv[1]);
    if (idx < 1 || idx > num_students) {
        printf("Invalid index, should be between 1 and %d\n", num_students);
        return -1;
    }
    printGrades(idx);
    return 0;
}
