// Generated by Claude 3.5

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct Course {
    char *courseName;
    int courseCode;
};

struct Student {
    char *name;
    int age;
    struct Course *enrolledCourse;
    float *grades;
    int numGrades;
};
typedef struct Student Student;

void printUsage() {
    printf("Usage: ./program <student_name> <age> <course_name> <course_code> <grade1> [grade2] [grade3] ...\n");
    printf("Example: ./program \"John Doe\" 20 \"Computer Science\" 101 85.5 92.0 88.5\n");
}

void updateStudentInfo(struct Student *student, const char *newName, int newAge) {
    if (student == NULL || newName == NULL) {
        printf("Invalid input parameters\n");
        return;
    }

    if (student->name != NULL) {
        free(student->name);
    }

    student->name = (char *)malloc(strlen(newName) + 1);
    strcpy(student->name, newName);
    student->age = newAge;
}

int main(int argc, char *argv[]) {
    // Check minimum required arguments (program_name + 5 required args = 6)
    if (argc < 6) {
        printf("Error: Insufficient arguments\n");
        printUsage();
        return 1;
    }

    // Parse basic information
    const char *studentName = argv[1];
    int age = atoi(argv[2]);
    const char *courseName = argv[3];
    int courseCode = atoi(argv[4]);

    // Validate age
    if (age <= 0 || age > 120) {
        printf("Error: Invalid age (must be between 1 and 120)\n");
        return 1;
    }

    // Validate course code
    if (courseCode <= 0) {
        printf("Error: Invalid course code\n");
        return 1;
    }

    // Calculate number of grades provided
    int numGrades = argc - 5;  // Subtract program name and other required args
    float *grades = (float *)malloc(numGrades * sizeof(float));

    // Parse grades
    for (int i = 0; i < numGrades; i++) {
        grades[i] = atof(argv[i + 5]);
        // Validate grade
        if (grades[i] < 0 || grades[i] > 100) {
            printf("Error: Invalid grade %f (must be between 0 and 100)\n", grades[i]);
            free(grades);
            return 1;
        }
    }

    // Create course
    struct Course course;
    course.courseName = (char *)malloc(strlen(courseName) + 1);
    strcpy(course.courseName, courseName);
    course.courseCode = courseCode;

    // Create student
    struct Student student;
    student.name = NULL;
    student.enrolledCourse = &course;
    student.grades = grades;
    student.numGrades = numGrades;

    // Update student information
    updateStudentInfo(&student, studentName, age);

    // Print student information
    printf("\nStudent Information:\n");
    printf("------------------\n");
    printf("Name: %s\n", student.name);
    printf("Age: %d\n", student.age);
    printf("Course: %s (Code: %d)\n",
           student.enrolledCourse->courseName,
           student.enrolledCourse->courseCode);

    printf("Grades: ");
    for (int i = 0; i < student.numGrades; i++) {
        printf("%.1f ", student.grades[i]);
    }
    printf("\n");

    // Calculate and print average grade
    if (student.numGrades > 0) {
        float sum = 0;
        for (int i = 0; i < student.numGrades; i++) {
            sum += student.grades[i];
        }
        printf("Average Grade: %.2f\n", sum / student.numGrades);
    }

    // Free allocated memory
    free(course.courseName);
    free(student.name);
    free(student.grades);

    return 0;
}
